apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: desertkido/detection-app:{{ .Values.env.APP_VERSION }}
        ports:
        - containerPort: 3000
        readinessProbe:
            httpGet:
                path: /health
                port: 3000
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
          httpGet:
              path: /health
              port: 3000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: nodejs-app-secrets
              key: EMAIL
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: nodejs-app-secrets
              key: EMAIL_PASS
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: nodejs-app-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PW
          valueFrom:
            secretKeyRef:
              name: nodejs-app-secrets
              key: RABBITMQ_PW                
