apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secrets
type: Opaque
data:
  EMAIL: dmFjemkub3R0aUBnbWFpbC5jb20=
  EMAIL_PASS: b3VyZiBmeXdwIG50cWEgYW5jeA==
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PW: Z3Vlc3Q=
