name: Static Code Analysis

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install
        working-directory: /home/runner/work/vehicle-detection/vehicle-detection/app

      - name: Run static code analysis
        run: npm run lint  
